### ISSUE TITLE
Display all Structure and Conveyance ID labels

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#268] opened 2018-07-11 19:16 UTC
Currently, all Structure and Conveyance ID labels do not always display, even if both label layers are turned on (see snip below). I am guessing it has to do with preventing overlapping labels but DelDOT has stated that they need to have the ability to see all the IDs because they had an instance where they could not get the one label they wanted to show to display on the map. They are open to suggestions and not opposed to leader lines. 

![image](https://user-images.githubusercontent.com/16919898/42594442-351bc742-851d-11e8-92a1-d3487e41bc9d.png)

**Comment by leeensminger** [comment] 2018-11-12 13:21
@impittman I think this might be able to be resolved by modifying the labeling engine settings within the mxd (vm-arcgis103 as gs_admin, then C:\DelDOTDev (I think)).  Please make a local copy of the mxd, then adjust settings as needed to fix the issue, then let me know here.

**Comment by impittman** [comment] 2018-11-13 19:34
@leeensminger logged into this VM as admin. I did not find the folder or a similar Dev for NPDES and did not want to edit the wrong MXD.

**Comment by impittman** [comment] 2018-11-15 15:10
@leeensminger I made a local copy of the mxd and it is here:
V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Geospatial_Solutions\Staff\MARIA\target_viewer_npdes_101_Label_Option_IMP

Adjusted the overlapping settings from high to medium, allowing both Conveyance and Structure labels to appear on the mxd. 

You may eventually want to consider dynamic text vs scale size to allow the text of the label to increase or decrease based on the scale of the map. For instance, a scale of 1:2000 currently still has large text and it looks jumbled. If you made it dynamic, the text would shrink in size down to scale. Just an idea for further dev.

**Comment by leeensminger** [comment] 2018-11-16 13:16
@cstevenson1 can you please pop open Maria's mxd, and see how these labels look to you?  If you think it looks ok we can publish in dev.

**Comment by cstevenson1** [comment] 2018-12-04 18:44
@impittman @leeensminger what version is the MXD? I have been unable to open it (we have 10.3.1)

**Comment by leeensminger** [comment] 2018-12-06 12:48
@impittman can you resave the mxd in 1031??

**Comment by impittman** [comment] 2018-12-06 18:04
@leeensminger @cstevenson1 
updated the map to 10.3 version, use this one here, confirmed it worked after the restart of the services :
V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Geospatial_Solutions\Staff\MARIA\target_viewer_npdes_101_Label_Option_IMP_103

**Comment by cstevenson1** [comment] 2018-12-12 19:36
All labels display in the MXD but still curious on the level of effort and effectiveness of the dynamic text Maria suggested. The labels are difficult to read when there are more than a few features in view.

**Comment by impittman** [comment] 2018-12-13 17:10
So I thought this through a bit more after the edits were publish and have the following comments:
1) The MXD definitely would need some dynamic text when viewing the labels. This is because the size of the text is static, let’s say 10 font regardless of the map scale. This is a relatively easy script to write into the label. I did similar for plot size in acres.
2) However, in taking the whole picture into play, MXD vs Published Map, it appears that the map text does alter based on Zoom level. I tested this concept and captured the labels in MXD vs the Dev NPDES Viewer environment with the updated label settings now displaying (see below).
3) If the MXD is just acting as the template for the published map, I don’t think we need to take step 1 based on my testing this morning and conversing with Lee. Adding in the new label settings in the published map helped to confirm this.

In MXD – Labels remain same size 
![mxd](https://user-images.githubusercontent.com/16418393/49955024-d335bd80-fecf-11e8-8743-07f7ac9d2007.jpg)

In Web Viewer – Then as you zoom in more the remaining Conveyances/Structures populate, kind of like Google Maps
![web viewer](https://user-images.githubusercontent.com/16418393/49955050-df217f80-fecf-11e8-9e68-dc8c8b8cbc27.jpg)

**Comment by leeensminger** [comment] 2018-12-24 16:40
@cstevenson1 please confirm if we are approved to deploy the updates (as reflected in the mxds Maria provided) to production

**Comment by cstevenson1** [comment] 2018-12-28 15:42
KCI Newark discussed and we think the labels are better but not necessarily ideal since they are still fairly jumbled. We don't know if there is another option though and agreed to deploy these updates and can log enhancements based on DelDOT feedback if needed.

**Comment by leeensminger** [comment] 2019-01-11 11:51
One thing you could consider is show less labels in the map.  Cartographically speaking, there is way too much information being displayed, and one of the downsides is that things look jumbled.

Or only turn on conveyance labels when zoomed WAY in.

**Comment by leeensminger** [comment] 2019-01-11 11:51
@impittman please coordinate with Lu to publish these mxds to dev, then upon approval from Newark, push to prod.

**Comment by impittman** [comment] 2019-01-11 12:48
@kanglu666 
Please take this mxd and place into Dev. It contains the structures/conveyance labels need for this issue. 
V:_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Geospatial_Solutions\Staff\MARIA\target_viewer_npdes_101_Label_Option_IMP_103

**Comment by kanglu666** [comment] 2019-01-18 03:32
npdes map service has been published in dev, ready for testing

**Comment by cstevenson1** [comment] 2019-02-11 17:40
cannot test. structures/conveyances are not displaying in dev. I can query features but cannot see the symbology on the map.

**Comment by impittman** [comment] 2019-02-13 01:43
feature service has been updated in dev and appears to be working upon testing

**Comment by cstevenson1** [comment] 2019-05-30 13:57
@leeensminger The clutter caused by the overlapping labels is not being received well. We need to brainstorm other items that will allow users to see labels when needed but not overwhelm the map, which I know is difficult due to the sheer number of features. I don't know if its even possible but a way for the user to choose which features display the label or a quick access to turn them on and off

**Comment by cstevenson1** [comment] 2019-08-02 17:02
per discussion between GSG and WR - on hold. Newark to play with label engine

**Closed** 2019-08-02 17:04 UTC
Labels: FY20-Reviewed, Ready For Testing in Dev
