### ISSUE TITLE
Add Line for Maintenance Area Work Order in BMP Sandfilter Report

### ISSUE THREAD

**Issue by gerrykelly** [leeensminger/DelDOT-NPDES-Viewer#322] opened 2019-04-15 21:27 UTC
Similar to issue #308 we will need to add a line to the Structures Report for Maintenance Area (Work Order). Please use the field WORK_ORDERS.MAINT_AREA_WORK to populate this field in the report.

**Comment by gerrykelly** [comment] 2019-04-16 18:40
done in dev and prod

**Comment by gerrykelly** [comment] 2019-04-16 21:23
Ready for test (working in dev, -- prod will requires another update when WORK_ORDERS.MAINT_AREA_WORK added)

**Comment by cstevenson1** [comment] 2019-04-19 18:29
confirmed line has been added in dev and prod. will test again after the additional update is made 
![image](https://user-images.githubusercontent.com/16919898/56438027-8fa0f500-62af-11e9-94c7-67eddee32741.png)

**Comment by cstevenson1** [comment] 2019-06-18 16:56
@leeensminger is WORK_ORDERS.MAINT_AREA_WORK the correct spot for BMPs/Sand Filters? That table is currently for MS4 work orders and BMP work orders are handled outside the app. The field on the report should be sourced to a new field in the BMP DSF inspections table since the work order is specific to the inspection.

**Comment by kanglu666** [comment] 2019-08-26 01:20
MAINT_AREA_WORK filed has been added into BMP_DSF_INSPECTION_DRY table in dev database

**Comment by gerrykelly** [comment] 2019-09-03 21:40
@KCI-Ablowers
So, in this case it seems like it is still simply a matter of adding the dev code related to WORK_ORDERS.MAINT_AREA_WORK to prod, once the field exists in prod (which it still does not). So nothing for me to do until then.

**Comment by gerrykelly** [comment] 2019-09-03 21:47
@KCI-Ablowers 
This is new work since it was not deployed in dev as expected before.  But, shouldn't that new MAINT_AREA_WORK field have a domain assigned to it?  (that won't affect me here since we now keep our domain values and descriptions identical, but it's good practice for QC, etc.)

**Comment by gerrykelly** [comment] 2019-09-03 21:57
@KCI-Ablowers
I see what to do here, but just noting that BMPS and WORKORDERS have a direct relationship in the GDB. So the original code I had would have worked except that no BMP is actually related to a WO. I would recommend deleting that relationship class, and if what Lee said as "work order is specific to the inspection", then RCs should be created for WO<>BMP_INSPECTION & WO<>BMP_DSF_INSPECTION_DRY

**Comment by gerrykelly** [comment] 2019-09-03 22:40
@KCI-Ablowers 

Updated in dev, please assign back to me when ready for prod.
Note so far as testing in dev, the reports often fail because of AGS problems .., the dev services should really be moved to a server.  Restarting the http://vm-city102:6080/arcgis/rest/services/DelDOT_NPDES_Reports
service always "fixes" this (if not then it is likely a Python code issue I need to fix).

**Comment by cstevenson1** [comment] 2019-09-04 13:55
@KCI-Ablowers 

Confirmed field added to BMP_DSF_INSPECTION_DRY
![image](https://user-images.githubusercontent.com/16919898/64259260-c2622780-cef6-11e9-8cb4-6af82eac5c67.png)

Confirmed field was used for Dev Sand Filter Reports
![image](https://user-images.githubusercontent.com/16919898/64261179-1ae6f400-cefa-11e9-8ec8-17bd544c7111.png)

**Comment by KCI-Ablowers** [comment] 2019-09-04 15:59
@cstevenson1 confirmed changes in Dev.

@gerrykelly I will assign this task back to when the schema update is in Prod.

**Comment by cstevenson1** [comment] 2019-09-10 19:00
[MAINT_AREA_WORK_domain.txt](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/3597331/MAINT_AREA_WORK_domain.txt)
per #309

**Comment by kanglu666** [comment] 2019-09-28 18:01
MAINT_AREA_WORK filed has been added into BMP_DSF_INSPECTION_DRY table in PROD database

**Comment by cstevenson1** [comment] 2019-10-07 11:30
@KCI-Ablowers appears to be working in PROD with the new values

![image](https://user-images.githubusercontent.com/16919898/66308140-46cc0f80-e8d4-11e9-9265-20ce1636f83e.png)

**Closed by cstevenson1** 2019-10-07 11:30 UTC
Labels: FY20-Reviewed, Lu Milestone 1, Push to Prod - Confirmed, reports
