### ISSUE TITLE
Add line in BMP Report for Maintenance Area (Work)

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#308] opened 2019-03-06 01:13 UTC
Please add a spot directly BELOW the existing Maintenance Area field int he BMP report.

The existing Maint Area field captures the actual geography of where the BMP is.
We need a spot in the report that identifies which maintenance area is actually doing the repair work (because they are not always the same).

For now, there is no source for this field.  We simply need to create the space, so Newark can manually add the value.  We are working on adding a field to support this.

![image](https://user-images.githubusercontent.com/4103847/53755322-3d814d00-3e84-11e9-8816-5c021ee4636e.png)

**Comment by gerrykelly** [comment] 2019-03-06 16:39
@leeensminger 
I simply added (in dev and prod) a carriage return to the label and value like ...
![image](https://user-images.githubusercontent.com/8259136/53897567-69c3d780-4004-11e9-9b85-8d1feb9fc800.png)
... and checked that the table still remains entirely on the page.

Let me know if you want another label .... a gridline ....

**Comment by leeensminger** [comment] 2019-03-17 23:24
@gerrykelly yes, actually, we need another label/gridline.  The label can read [something] - need to confirm with Christina.

@cstevenson1 what is the preferred label?  perhaps "Maintenance Area (Executing)"?

**Comment by cstevenson1** [comment] 2019-03-18 16:49
@leeensminger Below is a snip from a BMP Report Ryan submitted to DelDOT. They want the label formatting to be the same (excluding the word "Area" before the maintenance area number). The value for Maintenance Area (Work Order) may be a little longer since it is a manual text field with the area and supervisor name but should not be significantly longer. 

![image](https://user-images.githubusercontent.com/16919898/54547176-9d472000-497b-11e9-9da3-b327186b32dc.png)

**Comment by leeensminger** [comment] 2019-03-18 17:11
@gerrykelly please create a separate GH item if you think its necessary, but please:
1) Add "(Location)" to the existing maint area field
2) Add the second gridline with "Maintenance Area (Work Order)"

Please ensure the parenthesis items are on a new line, as shown in the image.

**Comment by gerrykelly** [comment] 2019-04-02 16:51
@leeensminger 
Updated in dev and prod, please review

**Comment by cstevenson1** [comment] 2019-04-04 18:22
@leeensminger the line has been added but Gerry will need to source it to the new field in the database once it is added. Is that being covered under this bug?

![image](https://user-images.githubusercontent.com/16919898/55578921-08675500-56e5-11e9-9f00-41a45d574e13.png)

**Comment by impittman** [comment] 2019-04-08 11:52
@gerrykelly please link the Mainteance Area (Work Order) field to the following field recently created in DEV:
deldot_migration2.DBO.WORK_ORDERS.MAINT_AREA_WORK

**Comment by gerrykelly** [comment] 2019-04-16 21:41
Ready for test (working in dev, -- prod will requires another update when WORK_ORDERS.MAINT_AREA_WORK added)

**Comment by cstevenson1** [comment] 2019-06-18 16:49
@leeensminger is WORK_ORDERS.MAINT_AREA_WORK the correct spot for BMPs/Sand Filters? That table is currently for MS4 work orders and BMP work orders are handled outside the app. The field on the report should be sourced to a new field in the BMP inspections table since the work order is specific to the inspection.

**Comment by kanglu666** [comment] 2019-08-26 00:57
MAINT_AREA_WORK  has been added into table BMP_DSF_INSPECTION_DRY
in dev database

**Comment by gerrykelly** [comment] 2019-09-03 21:57
@KCI-Ablowers 
I see what to do here, but just noting that BMPS and WORKORDERS have a direct relationship in the GDB.  So the original code I had would have worked except that no BMP is actually related to a WO.  I would recommend deleting that relationship class, and if what Lee said as "work order is specific to the inspection", then RCs should be created for WO<>BMP_INSPECTION & WO<>BMP_DSF_INSPECTION_DRY

**Comment by gerrykelly** [comment] 2019-09-03 22:41
@KCI-Ablowers

Updated in dev, please assign back to me when ready for prod.
Note so far as testing in dev, the reports often fail because of AGS problems .., the dev services should really be moved to another server. Restarting the http://vm-city102:6080/arcgis/rest/services/DelDOT_NPDES_Reports
service always "fixes" this (if not then it is likely a Python code issue I need to fix).

**Comment by cstevenson1** [comment] 2019-09-04 12:49
Confirmed field has been added in Dev database to BMP_INSPECTIONS table.
![image](https://user-images.githubusercontent.com/16919898/64255366-3698cd00-ceef-11e9-8f3c-9b880bbd1582.png)

Confirmed field was used for Dev BMP reports.
![image](https://user-images.githubusercontent.com/16919898/64256050-a0fe3d00-cef0-11e9-8399-88b11ef58099.png)

@KCI-Ablowers please push to prod

**Comment by cstevenson1** [comment] 2019-09-04 12:55
@KCI-Ablowers 
@gerrykelly is correct that currently no BMPs are associated with a work order. The existing work order tables are specific to structures and conveyances. BMP work orders have been handled outside of the database because it was deemed too big of an effort to integrate into the database at this time. The changes made from this bug may only be a temporary fix until we can address the larger BMP work order problem.

**Comment by KCI-Ablowers** [comment] 2019-09-04 13:18
@cstevenson1 confirmed changes in Dev. 

@gerrykelly I will assign this task back to when the schema update is in Prod. I agree with @cstevenson1's second comment but will double-check the relationship delete you suggested with @kanglu666 and BC.

**Comment by KCI-Ablowers** [comment] 2019-09-10 16:55
As long as pushing this to won't affect any existing workflows, I think it should go through as-is, but asked BC to review. I will update this comment if necessary.

Push to Prod - Confirmed.

**Comment by kanglu666** [comment] 2019-09-28 18:00
MAINT_AREA_WORK has been added into table BMP_INSPECTION in PROD

**Comment by gerrykelly** [comment] 2019-09-29 16:39
@KCI-Ablowers 
Working in prod

**Comment by cstevenson1** [comment] 2019-10-07 11:25
@KCI-Ablowers appears to be working in PROD with the new values 

![image](https://user-images.githubusercontent.com/16919898/66307862-92ca8480-e8d3-11e9-8dc6-3236aff6ebea.png)

**Closed by cstevenson1** 2019-10-07 11:25 UTC
Labels: FY20-Reviewed, Lu Milestone 1, Push to Prod - Confirmed, reports
