### ISSUE TITLE
BMP Report - Inspection Parameter Action Update

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#216] opened 2017-11-17 17:17 UTC
Each inspection parameter  has a 

- Score (D_Insp_Score)
- Comment
- Action(s) - _each action has a:_
  - Action Type
  - Action statement
  - Comment
  - Score (as measured by D_Insp_Score) _this is not currently carried in the database_

D_Insp_Score is:

	• 0 - Not Applicable
	• 1 - No Issues
	• 2 - Minor Issues not Affecting Performance
	• 3 - Maintenance Work Order / Invasive Spray
	• 4 - Contracted Work
	• 5 - Reftrofit

Users will input the action score into the existing Action Comment field using defined characters.  Based upon the score, the action will display within the report in one of the following tables:
- Minor Issues(s) Not Affecting Performance
- Maintenance Work Order
- Contracted Work
- Retrofit

The action score will be mapped to the tables as follows:
@cstevenson1 @mortynsky Please advise for what happens for score 0, score 1, and when no score is present in the comment.

Score | Action Comment   Syntax | Report Table
-- | -- | --
0 | @0@ | ?
1 | @1@ | ?
2 | @2@ | Minor Issues(s) Not   Affecting Performance
3 | @3@ | Maintenance Work   Order
4 | @4@ | Contracted Work
5 | @5@ | Retrofit

The action details (action type, action, comment) will be written to the report tables using the same requirements as previously detailed in GitHub (including but not limited to #128, #88 , etc.)

**Comment by leeensminger** [comment] 2017-11-17 17:22
@cstevenson1 @mortynsky Rules for notating the score with the symbols:

1. Don't use the @ symbol for anything except denoting the score (i.e., a comment of "Cattails @ the edge" would be bad).
2. Anything text between the @ symbols is ignored, except for a number 0-5.  Put any text you want there, but only a single number value, and only in that range.

**Comment by gerrykelly** [comment] 2017-11-17 17:29
@leeensminger @cstevenson1 @mortynsky 
Actually so long as the score is someplace between 2 @'s, whatever comes after the 2nd @ is fine, so the following is OK:
@2@Cattails @ the edge
or
@Score of 2@Cattails @ the edge
but not
@2 Cattails @ the edge

**Comment by gerrykelly** [comment] 2017-11-17 17:48
@leeensminger @cstevenson1 @mortynsky 
To clarify -- particularly what the problem is with that third example:
1) in the first 2 examples the parsing routine will find any number between the leading @ and the next @, so the score is recognized as 2 and the comment is then parsed out after the 2nd @, so you get 'Cattails @ the edge'  as the comment in the report.
With that 3rd example what goes wrong is that, while the score is picked up as '2', the word 'Cattails ' is seen as meaningless text between the leading @ and 2nd @ and you comment is the unintended ‘ the edge’ by the parsing logic.

**Comment by cstevenson1** [comment] 2017-11-28 15:02
If Score = 0, 1, or Null then the action item should not appear in the BMP report. These are user errors and should be flagged during the QC process to be corrected so that they appear in the correct place when the report is exported.

@leeensminger to help Newark with field calculating the scores for historical inspections.

**Comment by gerrykelly** [comment] 2018-05-15 17:28
@leeensminger 
Your turn to enjoy this.  Based on yesterday's discussion you should understand why you are seeing what you are seeing and why it is (hopefully) "correct" within the existing logic for scores in the inspection table and now having individual action scores.
 - So there are (legitimately) two ways that inspection actions get into the Minors table
   - in the particular case that action with a score of 5 getting in Minors is bogus, bc it would really have a score of 2
     - I set the score to 2 (and since set it back to 5) bc I knew I would need to prevent the same action record from showing up in Minors twice (because it gets queried in both ways.  You can verify that it works and only shows up once if you'd like.

Now for the 3,4,5 scores embedded in the comments, those actions go into a single table named according to the greatest severity.  This table is at the end of the report and titled "ACTION ITEM SUMMARY --- from individual action scores".  The original table that is between the ACTION ITEM SUMMARY MAP & Minors is still generated according to our existing logic.  It's likely you want to come up with some blend of scoring logic that coalesces these to one table.  That requires some thought since you need to cover all the variations of actions related to an inspection having all, some or none with comments and what the impact is of an action(s) having a score different (I guess with good data "different" would always mean "lower").  Keeping the tables separate until if and when you define that logic let's you test and consider what the final intended result would be.

**Comment by cstevenson1** [comment] 2018-10-15 18:05
Actions Items with a Score of 2 appear to be duplicated; appearing in the Minor Issue(s) box where is belongs and in the main Contracted Work box. The @ symbols should also be removed from the comment when placed in the minor issues box.

![image](https://user-images.githubusercontent.com/16919898/46969190-43b48f80-d083-11e8-9fe0-6529279a2dc4.png)

**Comment by cstevenson1** [comment] 2018-10-15 18:31
It also appears to be duplicating some of the action items at the very end of the report. The heading on the duplicated items says "ACTION ITEM SUMMARY --- from individual action scores"

Page 4 of 2018 BMP 9 Report

![image](https://user-images.githubusercontent.com/16919898/46970322-c5f28300-d086-11e8-9902-c9871c34dbea.png)

Page 8 of 2018 BMP 9 Report
![image](https://user-images.githubusercontent.com/16919898/46970354-d73b8f80-d086-11e8-8f7f-c9f199f639f7.png)

**Comment by gerrykelly** [comment] 2018-10-19 17:12
@leeensminger @cstevenson1 
From the original requirements ACTION ITEM SUMMARY (Contracted Work/Maintenance WorkOrders/Retrofits) was to include 
**Any** parameter _SCORE in BMP_INSPECTIONS = 3 or 4 or 5, and
(2)	 There are related records in BMP_INSPECTION_ACTION

I'm am revising this so that if for the related BMP_INSPECTION_ACTION the parameter _SCORE is less than 3 AND any embedded-in-the-comment score is less than 3, the action will not show up in ACTION ITEM SUMMARY

**Comment by gerrykelly** [comment] 2018-10-19 17:54
@leeensminger 
Just verifying that these 2 scores and actions are paired up right (that I don't have them reversed)

WQ_CONTAM_SCORE | 'WaterQC'
WQ_TREATMENT_SCORE | 'WaterQT'

**Comment by leeensminger** [comment] 2018-10-19 18:29
@gerrykelly Yes, correct.

**Comment by gerrykelly** [comment] 2018-10-23 18:20
@leeensminger @cstevenson1 
I revised, in dev, three reporting routines that deal with the actions and scores.  The behavior should now be that:
1) The action/info will be included in the ACTION ITEM SUMMARY ... If an action scores 3 or higher from EITHER the "*_SCORE" field from the inspection or from a score embedded in the inspection action comment
2) If _only_ the embedded score is >=3 then the action info shows up only in the "ACTION ITEM SUMMARY --- from individual action scores" section
       -- if there are no such cases for the inspection that section is not generated
3) So now the <3 scores should only show up in minors and there should be no duplication of actions in the report

**Comment by leeensminger** [comment] 2018-11-02 08:38
@cstevenson1 please test in dev

**Comment by cstevenson1** [comment] 2018-11-09 18:21
I don't think this is completely working. 

I can't generate reports on BMPs that are a D - Retrofit in the Dev Viewer but I can in Prod (I get a server error in Dev - examples include 192, 75, and 184 for 2018). 

I also couldn't get most of the A's I tried to generate. It may have to do with if the BMP has any action items with a score of 2 because I could generate the report for BMP 786 but could not for 208 in dev for 2018 inspection year. 786 has no associated action items and 208 does.

However BMP 31 (rated a B) has action items with 2s and 3s and that appeared to work correctly.

**Comment by gerrykelly** [comment] 2018-11-26 16:42
@leeensminger @cstevenson1 
I was unable to replicate these errors.  The dev AGS is known to be buggy and we really should move to a different server.  It should be the same code in the dev & prod GP service and the same data (to a point) in the dev and prod GDBs, so if we don't see a problem in prod but we do it dev it will usually be AGS

**Comment by leeensminger** [comment] 2018-11-28 12:22
@cstevenson1 Skype me when you work to retest this.  If you have the same issues as before in dev, let me know and I can restart the service to hopefully flush, temporarily, whatever is causing the issue.

**Comment by cstevenson1** [comment] 2018-12-18 13:00
So far so good. We have been able to generate reports, the @ symbols are gone and actions appear to be populating in the correct boxes for all of the ones we have checked.

**Comment by gerrykelly** [comment] 2019-01-23 17:07
@leeensminger @cstevenson1 
I think the BMP report code in dev and prod is now identical (and the reports I compared also are), please verify for one of your noted was-a-problem BMPs

**Comment by cstevenson1** [comment] 2019-01-29 18:56
@gerrykelly I don't think the code is identical. See BMP 82 - 2018 Inspection
The action with a 2 score shows up in the prod report twice (once in action items section and once in minor issues box at the bottom). That same action item only shows once in the dev report (minor issue section where it belongs)

PROD
![image](https://user-images.githubusercontent.com/16919898/51932675-9e24f200-23cd-11e9-9711-99948c2f4e19.png)


DEV
![image](https://user-images.githubusercontent.com/16919898/51932504-49817700-23cd-11e9-86e5-2b90ce5fdc55.png)

**Comment by gerrykelly** [comment] 2019-02-06 17:57
@leeensminger @cstevenson1 
The prod BMP report should now be in sync with dev, except for the maintenance area issue

**Comment by cstevenson1** [comment] 2019-02-07 15:45
Unable to generate report to test in prod. The loading spinning wheel to the left of the inspection year appears for a very brief second and then disappears. I had someone else try and they had the same result. I tried clearing cache and still no luck.

**Comment by gerrykelly** [comment] 2019-02-07 19:27
@leeensminger @cstevenson1 
I can't reproduce this from my side ... things look fine (as they did for me yesterday with the update)  I restarted the report service for what that's worth.
If this continues I need more info (at least for now a BMP# & year failing -- even if it's all of them on the UI side -- just so we are on the same page.  A developer may need to look at it from the UI side if I still don't see anything.

**Comment by cstevenson1** [comment] 2019-02-08 13:54
Still having the issue but noticed a shield in my address bar this morning when I tried again. The message was for unsafe scripts. I clicked allow and refreshed the page. When I tried again the URL turned red and said not secure.

![image](https://user-images.githubusercontent.com/16919898/52482302-e63ad600-2b7e-11e9-8cd3-49c0725a5e0f.png)

![image](https://user-images.githubusercontent.com/16919898/52482393-28641780-2b7f-11e9-8ad9-3bdbd0076330.png)

**Comment by cstevenson1** [comment] 2019-02-08 15:01
Just an FYI, the unsafe scripts mentioned above are occurring on all reports (Structure, Conveyance, BMP, and WQI). I can make this its own issue if needed.

**Comment by gerrykelly** [comment] 2019-02-08 15:09
@cstevenson1 @leeensminger 
Yes, this should be its own issue ... thanks

**Comment by leeensminger** [comment] 2019-02-08 15:10
@cstevenson1 please close this issue if the other functionality is good.  If you need to test it first, but are prevented from testing due to the unsafe scripts issue, then reassign yourself and hold until resolved.

**Comment by cstevenson1** [comment] 2019-02-11 17:04
@leeensminger @gerrykelly functionality is not good, same as before where level 2 action items are being duplicated. See 2018 reports for BMP 82 or 505

![image](https://user-images.githubusercontent.com/16919898/52579874-23a89900-2df5-11e9-8711-2bf48d790dd1.png)

**Comment by gerrykelly** [comment] 2019-02-11 19:11
@cstevenson1 @leeensminger 
I think this is fixed.  While the code for the BMP report was OK in prod, there was a difference in the app config file causing the error; now the config should match dev and work correctly.

**Comment by cstevenson1** [comment] 2019-02-15 17:16
@gerrykelly @leeensminger I think this is now working when the parameter only has one action item and it has a score of 2 like the examples above. However, I don't think it is working when a single parameter like overall site stability has multiple actions items and one is a 2 and the other has a score > 2. It appears to still be duplicating the 2s in those cases. See BMP 528 - 2018 inspection as an example.

![image](https://user-images.githubusercontent.com/16919898/52872818-6f23b580-311b-11e9-94a9-21fefccabe0d.png)

**Comment by gerrykelly** [comment] 2019-02-19 18:40
@cstevenson1 
The issue was basically as you thought it was.  I updated it in dev.  If verified fixed, Please check a couple of the cases other than where you saw problem to make sure nothing changed there.

**Comment by cstevenson1** [comment] 2019-03-07 20:09
Ryan and I think this is good now. Thanks Gerry

**Comment by gerrykelly** [comment] 2019-04-19 17:08
@leeensminger @cstevenson1 
Updated in prod

**Closed** 2019-05-03 13:06 UTC
Labels: Confirmed OK in dev - move to prod, priority item, reports
