### ISSUE TITLE
Print Widget - Submit button fails to display when printing multiple maps

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#278] opened 2018-10-24 16:44 UTC
@ehsan67 

On production - when printing a map (map export), the first time the map is generating is no problem.  The second, or sometimes third, time that a user closes and reopens the Print widget, the Submit button fails to display.  

On dev - when printing a map (map export), after the map is generated, the print widget displays the Download button, but not the Submit button.  Upon the user hitting Download, the Submit button is then displayed.

Steps to reproduce on prod:
Zoom in to keep performance faster.  
1. Open print widget.
2. enter name and size, then click submit.
3. After the map is generated, close the print widget.
4. Reopen print widget.  The Submit button is not displayed.  See attached image.
If the Submit button is displayed, repeat steps 2-4.

![l_a89a tmp](https://user-images.githubusercontent.com/4103847/47446993-7731a100-d78a-11e8-94fb-ab51dd81f9de.PNG)

**Comment by ehsan67** [comment] 2018-10-26 14:43
fixed in KCI dev

**Comment by leeensminger** [comment] 2018-10-26 15:07
@ehsan67 I do not see any difference in dev.  The behavior appears to be the same.  I'm wondering though if the workflow and system-responses described above are actually correct as is.

My suggestion would be to deploy to prod after-hours, and we can confirm there - since the primary issue was identified there (versus staging)

**Comment by ehsan67** [comment] 2018-10-26 15:20
@leeensminger  did you clear your cache? from my testing I realized the problem is when the user generates a pdf and instead of downloading, closes the print window. the next time the submit button won't be there. So I fixed that

**Comment by leeensminger** [comment] 2018-10-26 15:40
@ehsan67 Confirmed good.  please deploy to prod after business hours and confirm back when done.

**Comment by ehsan67** [comment] 2018-11-02 21:07
@leeensminger  done

**Comment by leeensminger** [comment] 2018-11-03 22:28
@cstevenson1 I tested this good in prod.  Please confirm.

**Comment by cstevenson1** [comment] 2018-11-06 15:44
I don't think it is functioning as planned. 

A map automatically comes up after clicking 'Submit' which is labeled as a bunch of number and letters in the tab heading. Then when I click download a new tab is created with the map that says MapPdf in the tab heading. You have to click 'Download' in order to get the submit button back so this essentially is making you create two maps.

![image](https://user-images.githubusercontent.com/16919898/48074924-fc1bb200-e1af-11e8-8139-471d1e42fae3.png)

**Comment by leeensminger** [comment] 2018-11-12 13:14
@impittman Please confirm you can reproduce, and if so, assign Ehsan with any additional notes as needed.

**Comment by impittman** [comment] 2018-11-12 17:15
I received the same results as @cstevenson1  Here are the steps I took to replicate:
1)	Zoomed in to an area with features.
2)	Clicked “Export Map pdf” icon to Print.
3)	Entered info in the parameters box:
![print fail](https://user-images.githubusercontent.com/16418393/48363608-50250b80-e674-11e8-96b6-81a049f7cb8f.png)
4)	Clicked “Submit” to generate the export pdf.
5)	The following appeared in the “Print Widget” box, with the only option to Download:
![print fail 2](https://user-images.githubusercontent.com/16418393/48363634-5ca96400-e674-11e8-8162-3f4fe7faaf8d.png)
6)	Clicked “Download” and the Submit Button appeared. I also had 2 copies of the exact map created in steps 1-5.
![print fail 3](https://user-images.githubusercontent.com/16418393/48363647-66cb6280-e674-11e8-8282-380cdd57cf2e.png)
7)	Repeated Steps 1-6 on 3 separate locations and received the same results.  Assigning back to @ehsan67

**Comment by kanglu666** [comment] 2018-11-18 01:02
Submit button fails to display issue has been fixed.
1:the Submit button will always shows, when the printing process is running, the button will be disabled.
once the process is done, the button will be enabled
2: the download button will show up once the submit button clicked and the printing process is done.
3: when user close the printing tool, then reopen the printing tool, the download button will not show up since this is an new printing process for user, then no map to download before click the submit button.

When the submit button clicked, the map with the number names directly coming from the printing gp service, this is only happen in PROD, and the map has no legend. the download button will create the map with legend from server and give new file name.

after testing, This behavior only happens in PROD, not in dev. I believe it did not happen in PROD before we switch to HTTPS.

**Comment by impittman** [comment] 2018-11-19 16:11
Here are the steps I took to validate the corrections:
1)	I believe there is a bit of a workflow change here to work around the map legend not showing in Prod. In order to get the full map with a legend:
a.	 The user Zooms to the area
b.	 Hits Map Export
c.	 Names the Map
d.	Clicks Submit
e.	The map generates in the a separate tab (windows explorer), the map does not include the legend as Lu noted 
f.	The user has to go back to the UI, click download and 2nd tab appears with the same Map to get the Legend.
g.	This works as Lu suggested

After speaking with Lee, steps E-G are not convenient to the workflow.  The map needs to produce the map with the legend in one step, not two, essentially eliminating step F above.

**Comment by kanglu666** [comment] 2018-11-29 01:43
latest esri javascript api version has been applied to the web viewer that fix the printing tool issue.
work flow:
a.	The user Zooms to the area
b.	Hits Map Export
c.	Names the Map
d.	Clicks Submit, when the printing is in process the "submit" button is disabled
f.	when the printing process is finished, the download button shows, user click download, an tab appears with the Map and related Legend.

**Comment by impittman** [comment] 2018-11-29 15:23
tested in Prod using IE, Chrome, Edge: worked as expected, believe the issue is resolved and closing

**Closed by impittman** 2018-11-29 15:23 UTC
Labels: Ready For Testing in Prod
