### ISSUE TITLE
Water Quality Investigation Report - Adding Unchecked Boxes

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#123] opened 2017-07-07 18:25 UTC
Add unchecked boxes next to all of the options that aren't checked as shown on the template. 

Report - 
![image](https://user-images.githubusercontent.com/16919898/27971238-e6ab3d24-631f-11e7-84c5-dfab3bcd835f.png)

Template - 
![image](https://user-images.githubusercontent.com/16919898/27971277-078c670c-6320-11e7-96e7-407869e2aa18.png)

**Comment by leeensminger** [comment] 2017-08-03 02:58
@cstevenson1 This is working correctly on Gerry's machine, and he double checked the code and that seems to be OK.  I reproduced the issue on my machine, though - so the thought is that this has something to do with specific PDF software or font support that is different for Gerry than for us.  Can you have a few other people in your office double check this, and see if they all get the same results?

**Comment by cstevenson1** [comment] 2017-09-14 11:12
Could it possibly be a browser issue? When the report pulls up in Chrome the check boxes don't show but once we download the report and it opens the report in Adobe, the check boxes do show. I think this can probably be an enhancement at best. Everyone here only has Chrome and IE.

Chrome
![image](https://user-images.githubusercontent.com/16919898/30426866-a2cdb5be-991b-11e7-97d3-f766f15a8ff7.png)

Adobe Acrobat Reader DC
![image](https://user-images.githubusercontent.com/16919898/30426888-b43860a6-991b-11e7-81cd-f81c09e02402.png)

**Comment by gerrykelly** [comment] 2017-09-14 18:01
@leeensminger @cstevenson1 
Then this definitely does seem to be an in-browser PDF viewer issue that I can't readily address.  When developing I make sure things look right in 2 PDF views (Adobe and Foxit) and that is really the standard where you can say it's a good PDF.  The in-browser view is a wildcard depending on the browser brand and a few other factors.  In my test here:
--The Doc looks perfect inside I.E. 11 (all good checkboxes)
--No empty checkboxes visible in Chrome
--In Firefox the empty checkboxes show as circles filled with vertical lines
So, open-in-reader it is :-)

**Comment by gerrykelly** [comment] 2017-09-14 18:06
@leeensminger 
Also, I checked with Lu and he does not see a way that from the web app we can force the PDF to open in a PDF reader (I kind of think it can be done, but don't want to waste more time on this).  So for now I think that it just needs to be a known issue that if you want the gold standard for the PDF it needs to be in a reader.

**Comment by leeensminger** [comment] 2017-09-14 23:38
@cstevenson1 Based on the discussions above, this needs to be an item communicated to DelDOT (when the time comes).  It sounds like we all agree this is complete and that we are up against some technical limitations of in-browser PDF viewing.  Since there's no more actual issue here, I'm closing this.

**Closed by leeensminger** 2017-09-14 23:38 UTC
Labels: Ready For Testing in next release
