### ISSUE TITLE
Update Base Map Data

### ISSUE THREAD

**Issue by impittman** [leeensminger/DelDOT-NPDES-Viewer#300] opened 2019-02-12 17:21 UTC
Please update the Base Map data using the MXD found here:
M:\2014\17141728.A\GIS\BaseData\Base_Data_Viewer

**Comment by kanglu666** [comment] 2019-02-13 03:55
published in dev, ready for testing

**Comment by impittman** [comment] 2019-02-13 14:19
The base data layer is missing in DEV. When I selected the Base Map drop down icon, nothing was listed as well. Steps taken:
1) Cleared cache - entire history cleared
2) Logged into Dev as Admin
3) Selected NPDES Web Viewer
4) Created a query, zoomed to a Structure
5) Discovered no base data was visible like centerlines, flowlines etc. 
![no base data 2](https://user-images.githubusercontent.com/16418393/52717917-385d6c00-2f70-11e9-9a2e-7aab41d6c50e.JPG)
6) Noticed the Base Data Layer was checked, clicked on the drop down icon to view items, nothing was there and the drop down icon went away once clicked.
![no base data 1](https://user-images.githubusercontent.com/16418393/52717974-5b881b80-2f70-11e9-952e-5da75beb4bb2.JPG)

**Comment by kanglu666** [comment] 2019-02-15 01:05
base map service has been re-published on dev, ready for testing

**Comment by impittman** [comment] 2019-02-15 16:01
this is updated as requested in Dev, @cstevenson1  please confirm this base map reflects all changes prior to pushing to prod

**Comment by cstevenson1** [comment] 2019-03-28 15:17
Issue @impittman noted on 2/13 is occurring again. Cannot test

![image](https://user-images.githubusercontent.com/16919898/55169339-02a0cb00-514b-11e9-90ca-e97b2e50d866.png)

**Comment by impittman** [comment] 2019-04-19 12:10
In Dev, tested today 4/19, and I see flow lines, center lines, etc: This may have been a server issue perhaps. See below:


![image](https://user-images.githubusercontent.com/16418393/56423533-85183880-627a-11e9-81ef-353d2a08ab82.png)

**Comment by cstevenson1** [comment] 2019-09-10 11:45
@KCI-Ablowers GSG to provide MXD for KCI Newark to update

**Comment by KCI-Ablowers** [comment] 2019-09-10 15:06
@cstevenson1 I assume this is the same MXD as the first comment - M:\2014\17141728.A\GIS\BaseData\Base_Data_Viewer. 

The data sources appear to be broken but can be restored using the database in that folder.

**Comment by cstevenson1** [comment] 2019-09-10 19:32
@KCI-Ablowers I believe that is the Sparks M drive so I am not sure where GSG is keeping the latest files. Last time I think it was shared with me through the V drive and then GSG copied it to the necessary file location for it to be consumed by the viewer.

**Comment by KCI-Ablowers** [comment] 2019-09-11 13:49
@cstevenson1 Do these MXDs look more familiar?


V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Geospatial_Solutions\Staff\MARIA\Field Tool MXDs

**Comment by KCI-Ablowers** [comment] 2019-09-17 18:30
@cstevenson1 Sorry I didn't assign this to you earlier. 

> V:_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Geospatial_Solutions\Staff\MARIA\Field Tool MXDs

Can you check the MXD at this path and see if it looks like the correct one?

**Comment by KCI-Ablowers** [comment] 2019-09-26 12:29
@cstevenson1 I checked with Lu and the MXD here - V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Geospatial_Solutions\Staff\ANDREW\DelDOT\Base_Data_Viewer is the most recent version.

**Comment by KCI-Ablowers** [comment] 2019-10-24 17:44
@cstevenson1 If the mxd in the above comment https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/300#issuecomment-535479697 isn't correct, could it be this one - V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\prod_mxds\prod_mxds\viewer\BaseData_1_Primary.mxd

**Comment by cstevenson1** [comment] 2019-12-17 12:49
@KCI-Ablowers MXD for base data to be used for all user group views is located at V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Geospatial_Solutions\Staff\ANDREW\DelDOT\Base_Data_Viewer\BaseData_Updates

**Comment by cstevenson1** [comment] 2020-01-09 14:19
@KCI-Ablowers Please make sure Seaford Maintenance Area is changed to Bridgeville Maintenance Area in the maintenance area layer of the base data to ensure it is consistent with the database and field tool.

**Comment by KCI-Ablowers** [comment] 2020-02-19 16:04
@kanglu666 Please review @cstevenson1's two comments above before proceeding.

**Comment by kanglu666** [comment] 2020-02-20 23:51
@cstevenson1  I'm not sure what you mean "Seaford Maintenance Area",
Could you please give me a screen shot for this? I need to know what the "Seaford Maintenance Area" is and where it is? Thanks

**Comment by cstevenson1** [comment] 2020-03-09 18:22
@KCI-Ablowers I confirmed Seaford was changed to Bridgeville in DEV.

Dev
![image](https://user-images.githubusercontent.com/16919898/76244837-387e7880-6211-11ea-88a9-66c03fbb528f.png)

Prod
![image](https://user-images.githubusercontent.com/16919898/76244864-43390d80-6211-11ea-8b94-2b51783f8042.png)

**Comment by mjuber-kci** [comment] 2020-03-13 14:30
**Cannot verify any of the scale extent changes are correct because of Bug #344 .** 

**Municipalities:** 40% transparency not working in map, but showing on exported map to PDF
Dev-
![image](https://user-images.githubusercontent.com/16919958/76628826-bc877780-6513-11ea-8805-a0bbaadaf397.png)

Exported PDF-
![image](https://user-images.githubusercontent.com/16919958/76628900-dde86380-6513-11ea-82f8-85728b92b711.png)

**Wetlands:** 40% transparency not working in map, but showing on exported map to PDF
Dev-
![image](https://user-images.githubusercontent.com/16919958/76628685-80541700-6513-11ea-8786-e95bd0b4f95d.png)

Exported PDF-
![image](https://user-images.githubusercontent.com/16919958/76628769-a4aff380-6513-11ea-9583-6c8458042bc4.png)

**Comment by kanglu666** [comment] 2020-03-21 20:42
Base Map service has been published in PROD, ready for testing

**Comment by mjuber-kci** [comment] 2020-03-24 13:40
40% transparency still not working correctly for Wetlands and Municipalities in the map in Prod, but is working in the Exported PDF. 

Prod Map - 
![image](https://user-images.githubusercontent.com/16919958/77431617-50c6c980-6db3-11ea-9a1e-8af70c85ba98.png)

Exported PDF - 
![image](https://user-images.githubusercontent.com/16919958/77431661-63d99980-6db3-11ea-8b9f-ddbef4a7f53b.png)

**Comment by KCI-Ablowers** [comment] 2020-10-15 00:52
@kanglu666 Please review and investigate.

**Comment by kanglu666** [comment] 2020-10-19 14:27
transparency issue has been updated in Dev, ready for testing in dev: 
 https://devgis.kci.com/deldotwebviewer/index.html

**Comment by cstevenson1** [comment] 2020-10-23 18:53
@KCI-Ablowers Transparency is coming through on the map which is good but with the Ortho on at 1(in):290(ft), the map was a greenish color.  Not sure if any of this is related or would occur as well when pushed to prod.

![image](https://user-images.githubusercontent.com/16919898/97042753-80070a00-153f-11eb-82e1-9e9ed5bf017a.png)

![image](https://user-images.githubusercontent.com/16919898/97042706-6fef2a80-153f-11eb-8316-81396979fe47.png)

**Comment by KCI-Ablowers** [comment] 2020-10-23 19:26
@kanglu666 any thoughts on the imagery?

**Comment by KCI-Ablowers** [comment] 2020-10-26 17:24
> @kanglu666 any thoughts on the imagery?
@kanglu666 do you know where the imagery is being sourced from? BC mentioned on our call today that it may be coming from aservice and this could be a bad tile.

**Comment by KCI-Ablowers** [comment] 2020-12-15 20:33
@kanglu666 This issue is back for the municipalities and wetlands layers in the viewer. Symbology appears correctly in the map export PDF. Please investigate.

**Comment by kanglu666** [comment] 2020-12-21 18:37
the transparency issue has been fixed in the dev, ready for testing.

The greenish color in the ortho is the bad tile in the image service. please test by changing a location

**Comment by KCI-Ablowers** [comment] 2021-02-23 16:42
https://firstmap.delaware.gov/arcgis/rest/services/DE_Imagery/DE_Imagery_2017/ImageServer

**Comment by KCI-Ablowers** [comment] 2021-06-22 17:42
@kanglu666 Can you replace the URL here - https://imagery.firstmap.delaware.gov/imagery/rest/services/DE_Imagery/DE_Imagery_2017/ImageServer and republish? I'm hoping that the tiles may be updated.

**Comment by kanglu666** [comment] 2021-06-23 17:58
new ortho map has been updated in dev viewer, ready for testing in dev

**Comment by KCI-Ablowers** [comment] 2021-08-23 13:59
Appears fixed in dev for this particular location - 

![Viewer_Imagery_Issue300_202010823](https://user-images.githubusercontent.com/35460336/130460243-5a65d2c0-19bd-4f27-96dd-31ad3ee013b3.png)

**Comment by KCI-Ablowers** [comment] 2021-09-02 00:46
Confirmed updated in Prod. Blue imagery does not appear in the area shown above at various scale ranges. https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/300#issuecomment-903797656


![image](https://user-images.githubusercontent.com/35460336/131763758-08e3e7c7-7beb-437a-8ba6-91cdf507d09c.png)

**Closed** 2021-09-08 14:09 UTC
Labels: priority item, Ready For Testing in Prod, FY20-Reviewed, MXD
