### ISSUE TITLE
Duplicate Structure and Conveyance Numbers (Reported by CS 20230120)

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#427] opened 2023-01-20 16:41 UTC
@cstevenson1 reported duplicate Structure (9) and Conveyance (21) in the database identified during a QC effort. @gerrykelly is going to run queries to identify those duplicates and provide some additional info (create date, etc.). @cstevenson1 to update this issue with more detail once she has had a chance to investigate (if necessary).

**Comment by KCI-Ablowers** [comment] 2023-01-20 17:08
From @gerrykelly 20230120 - 

![image](https://user-images.githubusercontent.com/35460336/213760806-f8d735be-2c79-4a9b-8b0d-82effb40b664.png)
![image](https://user-images.githubusercontent.com/35460336/213760823-cab538a6-8a12-441f-98cf-1688eb8d4baf.png)


[Duplicate Struct Convey Queries.txt](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/10468521/Duplicate.Struct.Convey.Queries.txt)

**Comment by cstevenson1** [comment] 2023-01-23 19:07
@KCI-Ablowers Since this appears to be a one off case where one set of IDs was assigned during the migration and the other set was assigned 6/12/2020, our plan is to recreate the structures/conveyances with duplicate IDs from 6/12/2020 so new unique IDs are assigned. I'm guessing there was a fluke with the nightly script that day and it failed to create unique IDs for all of the features. 

I'll close this issue once the features have been recreated and unique IDs are confirmed.

**Closed** 2023-01-27 16:23 UTC
Labels: priority item
