### ISSUE TITLE
DelDOT TSDM - BMP WO Processing Request

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#339] opened 2019-10-28 13:31 UTC
Matt's email on 10/28/2019 -

> All,
> 
> Please see the attached documents related to the BMP MWO processing we discussed at our last meeting.  The items highlighted in yellow are things that we still need to work through:
> 
> DelDOT BMP MWO Processing for GSG.docx
> 
> 1.	Supreet wants to have a Unique ID submitted for all MWOs (see logic highlighted in yellow for what we are proposing)
> a.	I will confirm this logic is OK with Supreet
> b.	GSG please confirm this workflow is doable/makes sense
> 2.	We need to determine how the system is going to handle BMP MWOs in the Central District (Areas 6 – 8).  These work orders are grouped based on the type of work order and then maintenance area, all other districts have work orders based on location.
> a.	See DelDOT Supervisor List - BMP Work Orders_Updated 07-25-19 for GSG.xlsx
> i.	Need to discuss logic further with GSG
> 
> Please let me know if you guys have any questions.
> 
> Thanks,
> 
> Matt

Attachments from matt's email. 

[Maximo Problem Codes for BMP-MAINT_UPDATED_3_20_17 for GSG.xlsx](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/3778715/Maximo.Problem.Codes.for.BMP-MAINT_UPDATED_3_20_17.for.GSG.xlsx)
[DelDOT BMP MWO Processing for GSG.docx](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/3778716/DelDOT.BMP.MWO.Processing.for.GSG.docx)
[DelDOT Supervisor List - BMP Work Orders_Updated 07-25-19 for GSG.xlsx](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/3778717/DelDOT.Supervisor.List.-.BMP.Work.Orders_Updated.07-25-19.for.GSG.xlsx)

@gerrykelly you should be able to get rolling with the information provided by Matt. They are still waiting to confirm the unique ID request with DelDOT. Christina said that the need for a unique ID comes from the potential for a BMP inspection to be resubmitted with little or no changes the following year. We also still need to figure out the best solution to deal with the central district. My guess would be we will go with the text-based option.

**Comment by gerrykelly** [comment] 2019-10-28 18:19
@KCI-Ablowers 
The logic described -- since it involves BMP_INSPECTIONS but not BMP_DSF_INSPECTION_DRY -- means that the queries will not include sand-filter BMPS.  Just making sure that is known and intentional.

**Comment by gerrykelly** [comment] 2019-10-28 21:08
@KCI-Ablowers 
We can decided if we need to alter the approach later but the content of DelDOT Supervisor List - BMP Work Orders_Updated 07-25-19 for GSG.xlsx needs to exist as a real table someplace.  For now I created new table -- DelDOT_Maximo_Supervisor_List -- in dev.  

- In contrast the data from Maximo Problem Codes for BMP-MAINT_UPDATED_3_20_17 for GSG.xlsx should be static and is just key-value pairs, so I have that hard-coded as a "table" within my BMP workorders query itself.  If any new values were added to the corresponding domain, etc.  the view that will come out of this work would need to be edited directly.

**Comment by KCI-Ablowers** [comment] 2019-10-29 12:57
@gerrykelly the lookup table - deldot_migration2.DBO.LU_DISTRICT_SUPERVISORS table in dev/prod has some of the values in that excel file (highlighted in green below). We could modify this table with permission from @cstevenson1 and co. but your new table is probably the best solution

![image](https://user-images.githubusercontent.com/35460336/67767103-4f70bb00-fa26-11e9-807d-6c4a647b0921.png)

**Comment by gerrykelly** [comment] 2019-10-29 15:28
@KCI-Ablowers 
From the Word doc:
i)	PARENT = BMP_INSPECTIONS.BMP_ID – Confirm with Supreet
(1)	Should be populated for all BMP Work Orders except:
(a)	Should be left blank for all work order records with a PROBLEM_CODE = MULTIPLE
(2)	**Should be populated with the KCIWONO for all other records**

That differs from the original Excel example (and what we did for structures/conveyances) .  In Excel, it looks to me that inspections with only one action do not get a parent ID and do get the function_code

I'll go with the Word doc since that is latest

**Comment by gerrykelly** [comment] 2019-10-29 15:41
@KCI-Ablowers 
And, related to the previous comment, the Word Doc does not describe how I get to "PROBLEM_CODE = MULTIPLE".  We assume it is from an inspection having more than one action.  So, now going back to the Excel example, I am going to use that and **NOT** the direction from the Word doc for direction on PARENT_ID, KCIWONO,PROBLEM_CODE, FUNCTION_CODE

**Comment by gerrykelly** [comment] 2019-10-29 16:54
@KCI-Ablowers 
I have created a view -- BMP_WORKORDERS -- in both the dev and prod DBs.  I know there is some nuance to come for special situations (beyond the Central district supervisor which is accounted for in the queries), but this view is my best take on what the end product should be given the Excel and Word docs.

Please review.

**Comment by cstevenson1** [comment] 2019-11-04 12:36
@KCI-Ablowers Supreet approved Matt's recommendation (using BMP_INSPECTIONS.GlobalID instead of BMPS.GlobalID)

![image](https://user-images.githubusercontent.com/16919898/68120038-50946300-fed2-11e9-84db-d06c4ba6889f.png)

**Comment by gerrykelly** [comment] 2019-11-06 15:52
@KCI-Ablowers 
I have created tables **in the DEV DB**, an registered them in ArcCatalog, that are a snapshot of the current BMP_WORKORDERS view:
-  BMP_WORKORDERS_DEV
-  BMP_WORKORDERS_PROD

**Comment by KCI-Ablowers** [comment] 2019-11-07 13:01
@cstevenson1 and @mortynsky Can you guys please review the tables @gerrykelly created in the **Dev DB** for the BMP work orders?

**Comment by cstevenson1** [comment] 2019-11-18 14:32
@KCI-Ablowers Overall the table looked good and is pretty close.

1. What would be the level of effort to have the @ symbol removed from the beginning of the comment which indicates the score for the action
![image](https://user-images.githubusercontent.com/16919898/69058331-772dc000-09e1-11ea-88d3-98c360d84b19.png)
2. Only actions with an @3@ score for an inspection with an Overall "B" rating should be included (i.e. the @2@ should be excluded from the submission, if there are any @4@ those are an error on our part because those inspections should be rated "C")
3. We need to discuss/finalize an approach for handling the Central District BMPs
4. Can we control how often this is delivered? We are currently only delivering this to DelDOT on a quarterly basis? (Maybe we can lump it with the MS4 work order submission)
5. We need to make sure only new work orders are sent (i.e. do not submit the same KCIWONO)
6. We should also discuss exporting out the associated reports from the viewer which should have a filename of KCIWONO.pdf. Matt/Ryan are currently including this in the submission.

**Comment by gerrykelly** [comment] 2020-01-08 19:58
@KCI-Ablowers 
I've addressed the first 3 issues from the previous comment as follows:
1. The @3@ are removed from the comments as are the new @21@ (or whatever AREA number) that can be at the end of the comments
2. I updated the SQL for this logic
3. Done to the best of my understanding (logic as described in my email to Matt yesterday).  I added a few @21@s to records in the dev DB.  While they are included in BMP_WORKORDERS, there is also a new view BMP_WORKORDERS_TWO_AREA that could be used to evaluate just the records that get added bc of an area number in the comment. (and the views in Prod are the same ... just no data to check by)

We need to develop rules for 4 & 5,  For 6, I can do something but want to clarify just what they are looking for so far as the report.  Is it just the BMP report for distinct combinations of BMP/Inspection, but with a different naming convention than the usual?  Seems like it's gotta be, but just making sure.

**Comment by gerrykelly** [comment] 2020-01-09 16:39
@KCI-Ablowers 
I updated the BMP_WORKORDERS view to account for the logic I got from Matt where the AREA in the comment overrides the BMP AREA so there are not duplicate records.

**Comment by KCI-Ablowers** [comment] 2020-01-13 19:26
@gerrykelly I will capture issues 4 and 5 above in my write up along with the structure/conveyance WOs.  

@cstevenson1 I believe Gerry's comment (quoted below) is correct. Can you confirm? - 

> as the report. Is it just the BMP report for distinct combinations of BMP/Inspection, but with a different naming convention than the usual? Seems like it's gotta be, but just making sure.

**Comment by KCI-Ablowers** [comment] 2020-01-17 16:06
@gerrykelly and @kanglu666 

## From Christina's email on 1/17/2019 - Struct/Convey and BMP WO Requests 

> Would it be possible to push prod data to dev as discussed and then for us to enter test data in Dev? Unlike the work orders for structures/conveyances, the work order process for BMPs is not as defined in the database. This has led to the introduction of workarounds, such as the @ symbol in action items. Since we have not implemented the @ methodology for Central District and field procedures have evolved, we would prefer to test/review the BMP logic on more current and accurate data if possible. 

I spoke with Brendan and he can perform the backup of dev and push prod to dev. However, I wanted to confirm with you both if there are any new objects that can either be pushed to production as is or temporarily unavailable until the dev backup is restored. Please let me know.

**Comment by KCI-Ablowers** [comment] 2020-02-17 14:26
@gerrykelly An update to the query - 

Only records with a `STATUS` = "Open" should be included/submitted. This field is only updated once DelDOT notifies Newark that the WO is closed.

**Comment by gerrykelly** [comment] 2020-02-25 20:18
@kanglu666 @KCI-Ablowers 

Lu, I might want to add fields (for now just in DEV) to the following tables (and, yes, through ArcCatalog to respect versioning):
- BMP_INSPECTIONS
- BMP_INSPECTION_ACTION
- WORK_ORDERS
- WORK_ORDER_PROBLEM_CODES

Is there any concern that additional fields would impact anything in the viewer, field tool and/or any process?

**Comment by gerrykelly** [comment] 2020-02-25 22:21
@cstevenson1 @mortynsky 
I have updated the BMP_WORKORDERS view to correct the one "central district logic" error that I found as identified in Matt's 1/22/2020 email.

To get back to that test scenario I needed to append the @AREA@ values to inspection action comments as I had previously done in dev for the inspection related to BMPs 94, 323, and 
300.

However with the data having been migrated from prod these BMPs now had 2019 inspection whereas before 2018 was the latest.  To get back to the original test case I then changed their 2019 inspection date year to 2018 and vice versa.

Please verify that the results are now as intended (if you are going to start using SQL Server Management Studio, wait until then).  If the results are now correct then edit other inspection action comments to test any scenario you can think of that this handful of records does not cover and you think might not be correctly handled.

**Comment by cstevenson1** [comment] 2020-03-06 20:32
@KCI-Ablowers @gerrykelly Still trying to check a couple special cases but overall, it looks significantly closer to the desired result. So far we have observed the following:
1.	The DESCRIPTION field should pull from the BMP_INSPECTION_ACTION table and the appropriate ACTION_TYPE associated with that record
2.	The value of “Multiple” in the PROBLEM_CO field should be ALL CAPS

**Comment by gerrykelly** [comment] 2020-03-09 17:21
@cstevenson1 @KCI-Ablowers 
Updated

**Comment by gerrykelly** [comment] 2020-04-17 15:49
@KCI-Ablowers 
Just assigning this back to you with knowing that we still need to decide how to proceed with 
#351

**Comment by KCI-Ablowers** [comment] 2020-07-01 18:10
Marking as "Push to Prod - Confirmed" but leaving open pending any feedback from DelDOT.

**Comment by KCI-Ablowers** [comment] 2020-08-26 17:52
@gerrykelly and @kanglu666 - We are good to move all of this to prod (new prod).

**Comment by gerrykelly** [comment] 2020-08-27 21:37
@KCI-Ablowers 
Completed

**Closed** 2020-09-01 14:40 UTC
Labels: DelDOT, Push to Prod - Confirmed, database
