### ISSUE TITLE
PID Documentation Cutting Off

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#422] opened 2022-07-05 19:17 UTC
@KCI-Ablowers @gerrykelly The WQI team has recently had a couple of water quality investigations that have been particularly long (lots of memo lines and photos). They have reported that not all of the memo text and photos are being pulled in the report from the viewer.

The two known cases are:

Structure # 0109216544 and PID Point OBJECTID 2463

**Comment by gerrykelly** [comment] 2022-07-05 20:24
@KCI-Ablowers 
@cstevenson1 I don’t know what made you lie about this issue, but I’m sure you had your reasons :-) But, seriously, I cannot reproduce it.  

From my testing and Andrew running the reports from the prod and dev viewers the only thing that makes sense now is that the report was dev, not prod.

So, let's take a step back and could you run the reports fresh from PROD and recheck?  If you still see this issue, we'll need to come up with a plan to diagnose it; so assign it back to me if you do and please record exactly what time you run the reports so I can investigate better.

**Comment by cstevenson1** [comment] 2022-07-06 12:29
@KCI-Ablowers 

@gerrykelly Just trying to keep you on your toes but....
[Structure 0109216544 WQI Report.pdf](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/9054501/Structure.0109216544.WQI.Report.pdf)

Can you send the report that generates for you? Both Julie and I tried again this morning from PROD (she doesn't even have access to dev so I know that's not where it was previously generated) and are experiencing the same issue. I attached the PDF that generates for us and notice how the last memo line is for February 12, 2021. Last photos are also from 2021. The date on the tracking form is from 2021, which is also wrong. I've copied and pasted the memo comment text straight from the database below and you can see there should be multiple 2022 entries with the latest being May 27, 2022.

11-30-2020;DNREC received report from resident John Mehoff regarding sand and dirt from Middletown Materials entering roadway and stream during rainfall.||DNREC forwarded report to DelDOT & NCC, who contacted KCI and requested an IDDE investigation.||A KCI field crew (Julie Scheu/Danielle Gruber) visited the site  to investigate.||There was sediment on the ground near the entrance to Middletown Materials.||Runoff containing sediment enters swale 0109001637 through a curb cut.||There was sediment on the pavement near the curb cut but there was no runoff from the site entering the swale at the time of investigation.||There was turbid water in swale 0109001637, which discharges to a nearby stream, however the turbid water was coming from outfall 0109216498 which does not receive drainage from Middletown Materials.@@12-11-2020;NCC issued NOV to property owner. ||Property owner has until 12-28-20 to contact Sara Esposito, DelDOT, to submit plan for removing illicit discharge.@@12-28-2020;DelDOT/NCC received response from Amber Moore, RainWise Environmental Solutions, regarding NOV. ||Ms. Moore stated Middletown Materials received NOV on 12-28-20 and therefore need an extension of 10 days to address concerns stated in NOV. @@01-07-2021;Ms. Moore sent response letter to DelDOT/NCC.||The letter stated the Facility has addressed all action items required by NOV and requested NOV be rescinded since activities performed by Middletown Materials were not directly observed to warrant cited violations. ||Ms. Moore stated sediment may be coming from adjacent properties that share driveway connecting to Cedar Lane Road.||Ms. Moore also suggested sediment is originating from embankment on opposite side of Cedar Lane Road.@@01-12-2021;DelDOT/NCC requested KCI re-visit site during rainfall to determine source of sediment. @@01-26-2021;KCI (Julie Scheu/Ryan Brouillette) visited site to investigate. ||It was raining lightly upon arrival and there was some runoff from entrance/driveway entering roadway swale. ||Sediment accumulation observed on pavement near Middletown Materials shared driveway, particularly along curbs.||Sediment observed above adjacent properties and beyond Middletown Materials gate such that the only possible source for the sediment was Middletown Materials.@@02-03-2021;DelDOT issued follow-up letter to Middletown Materials via RainWise (Amber Moore). ||The letter provided evidence excess sediment is coming from Middletown Materials site and outlines steps that must be taken to minimize turbid runoff. ||Middletown Materials' course of action must be confirmed within 10 business days from receipt of letter. @@02-12-2021;Amber Moore sent response letter to DelDOT. ||The letter stated the facility will take the following steps to prevent excess sediment from leaving site:||Site entrance will be evaluated for improvement. ||Riprap will be placed at curb cut near entrance culvert. ||Weekly street sweeping of Cedar Lane Road will be initiated. ||Facility will increase frequency of routine stormwater inspection program. ||KCI added this incident to the PID Watch List for re-inspection. @@05-26-2021;A KCI field crew (Julie Scheu/Melissa Juber) visited site.||Some sediment was observed along curbs near Middletown Materials entrance. ||No sediment was observed on Cedar Lane Road.@@08-06-2021;A KCI field crew (Danielle Gruber/Ryan Brouillette) visited site. ||Cedar Lane Road was clean and free of sediment. ||Minor sediment accumulation was observed near Middletown Materials entrance. @@11-11-2021;A KCI field crew (Julie Scheu/Danielle Gruber) visited site. ||Sediment was observed on Cedar Lane Road north of entrance northbound and south of entrance southbound.||Excessive sediment was also present near Middletown Materials entrance, particularly near curb cut. @@11-15-2021;DelDOT (Sara Esposito) contacted Amber Moore and Middletown Materials personnel. ||Amber Moore stated she would conduct site visit 11-18-21 and contact site to ensure sweeping is being conducted. ||Middletown Materials (Laura Korell) also stated she would talk to her employees. @@01-14-2022;DelDOT received complaint from citizen, Jenna Talia.||Ms. Talia stated Middletown Materials continues to create a mess on Cedar Lane Road.||Sara requested KCI investigate the site. ||A KCI field crew (Melissa Juber/Christina Stevenson) visited site.||Sediment and tire tracks were observed at the entrance and leading onto Cedar Land Road, there was accumulated sediment at the curb cut, and sediment was observed on Cedar Lane Road near the stream culvert north of the site. @@01-24-2022;DelDOT (Sara Esposito) contacted Amber Moore and Middletown Materials personnel and asked about street sweeping frequency. ||Amber stated she would schedule meeting with Middletown Materials to verify sweeping schedule and identify additional BMPs. @@01-28-2022;Amber Moore informed DelDOT Middletown Materials swept facility entrance on 01-27-22 and plans to increase sweeping frequency to three times per week.||The site will also perform daily sweeping of the entrance and monthly inspections to ensure tracking is minimized. ||The site will evaluate additional BMPs such as rumble strips and paving.||Long term BMPs will be identified within 30 days. @@02-03-2022;DelDOT received additional citizen complaints regarding mud/dirt on Cedar Lane Road. ||Residents are concerned about safety hazard created by muddy road conditions. @@02-07-2022;DelDOT (Sara Esposito) coordinated with Amber Moore to received weekly street sweeping logs from Middletown Materials. ||Middletown Materials are to sweep driveway/entrance and Cedar Lane Road daily, preferably in the evening after each day's activity.@@02-11-2022;KCI (Danielle Gruber/Melissa Juber) visited the site to investigate.||Sediment was observed along Cedar Lane Road coming from the Middletown Materials entrance.||Excessive sediment also observed at Middletown Materials entrance.@@02-15-2022;DelDOT (Sara Esposito) scheduled site meeting with Middletown Materials personnel and KCI due to ongoing resident complaints. @@03-10-2022;DelDOT (Sara Esposito) and KCI (Julie Scheu/Danielle Gruber) met on-site with Amber Moore and Middletown Materials (Jake Yohe).||Rumble strip (FODS) near site entrance/exit was observed.|| Sweeper truck was discussed, including whether sweeping is done under wet or dry conditions. ||Sweeping is currently done dry until spring when water will be used. ||Amber Moore and Jake Yohe stated they are considering paving more area near entrance.@@03-23-2022;Amber Moore informed DelDOT DNREC visited site due to complaints received from public regarding material tracking. ||Amber Moore stated sweeper truck is current not operational and they are looking for a company to perform sweeping.||DNREC had several observations/action items for Middletown Materials including implementing additional BMPS such as paved aprons and FODS, fix sweeper truck to ensure roadway is swept, and establish procedure for cleaning FODS.@@03-29-2022;DelDOT (Sara Esposito) contacted DNREC (Bill Tanner). ||Sara made DNREC aware DelDOT has been watching and addressing the site, and the site has been cooperative in implementing new measures.   @@05-27-2022;A KCI field crew (Julie Scheu/Michelle Knapp) visited site. ||Heavy rain began upon arrival. ||Turbid water was observed leaving site and along Cedar Lane Road.

**Comment by KCI-Ablowers** [comment] 2022-07-06 12:44
@cstevenson1 @gerrykelly I just generated the attached report for that structure in Prod and it has the 2022 notes and 18 photos. I am using the admin account which is in the 'DelDOT NPDES' group (not sure that matters). 
[Structure.0109216544.WQI.Report.pdf](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/9054737/Structure.0109216544.WQI.Report.pdf)

Here is the URL for the report - https://newarkgis.kci.com/deldotwebviewer/proxypage_net/proxy.ashx?https://newarkgis.kci.com/\arcgisserver\directories\arcgisjobs\deldotreports\makereport_gpserver\j233d3fd436d84a1fb31f2343d08fe79a\scratch\DelDOT_NPDES_WQ_INVESTIGATION_STRUCTURE_0109216544_report.pdf

**Comment by cstevenson1** [comment] 2022-07-06 13:09
@KCI-Ablowers @gerrykelly  Julie and I are both in the DelDOT NPDES group so I would assume that's unrelated. Melissa and I both cleared our cache and received the same result (no 2022 data). I also had Danielle try who has never downloaded that report before and she is not seeing the 2022 data. 

I exclusively use Chrome at the office so I tried Edge and still the same thing. Julie uses Firefox so it has been tried across multiple browsers. All attempts have been made from the Newark office though.

**Comment by KCI-Ablowers** [comment] 2022-07-06 13:45
@cstevenson1 Can you rerun the report in Prod and drop the URL in a comment?

**Comment by gerrykelly** [comment] 2022-07-06 14:05
@KCI-Ablowers @cstevenson1 
Christina, I'd be curious about the results of the following test:  
- Let's focus on the PID Point OBJECTID 2463
- Bring up the DEV version of that in in ArcMap and navigate to the relationed WQI, then memo.  Add the word DEV to the start of the last comment and end of last comment
- Then do the same with the PROD version, but with the word "PROD" (and delete that after we are done testing)
- Run the PROD and DEV reports and see what you get

**Comment by KCI-Ablowers** [comment] 2022-07-06 14:06
@cstevenson1 @gerrykelly  It looks like that URL is referencing Dev compared to my URL above - 

![image](https://user-images.githubusercontent.com/35460336/177568317-d8d0e7bd-cebe-4ff4-acc6-85c6aef60349.png)

**Comment by gerrykelly** [comment] 2022-07-06 14:11
@cstevenson1 @KCI-Ablowers 
So, maybe hold off on the test I outlined, since the URL issue might point at the evidence I was trying to get to.  Is the viewer from which the bad reports are being generated a different version from what Andrew was using when we tested yesterday?  Somehow the PROD version is referencing DEV it seems (and only for WQI ... that seems unlikely, but I don't know this side of things) ... so if that problem can be verified, what's the fix?

**Comment by KCI-Ablowers** [comment] 2022-07-06 15:58
@kanglu666 We need to check the config files for the Prod viewer and confirm there are no references to Dev GP services. Please review the comments above for context and we can discuss this evening (7/6/22) - https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/422#issuecomment-1176267170 and https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/422#issuecomment-1176202861

**Comment by kanglu666** [comment] 2022-07-07 01:07
Reports issue has been fixed in PROD. Please clear your browser cache and test.

**Closed** 2022-07-07 13:29 UTC
Labels: priority item, Ready For Testing in Prod

**Comment by KCI-Ablowers** [comment] 2022-07-07 13:44
@kanglu666 Can you please add a comment on this issue describing the problem and resolution? Thanks
